name: 'telegram_db'
version: '1.0.0'
config-version: 2

profile: 'telegram_db'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "logs"

models:
  telegram_db:
    staging:
      +schema: staging
      materialized: table
    marts:
      +schema: marts
      materialized: table
