version: 2

models:
  - name: dim_channels
    columns:
      - name: channel_id
        data_tests:
          - unique
          - not_null

  - name: dim_dates
    columns:
      - name: date_id
        data_tests:
          - unique
          - not_null

  - name: fct_messages
    columns:
      - name: message_id
        data_tests:
          - not_null
      - name: channel_id
        data_tests:
          - not_null
      - name: date_id
        data_tests:
          - not_null
    data_tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - message_id
            - channel_id